import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsEnum, IsObject, IsOptional, IsString, IsUUID, MaxLength } from 'class-validator';
import { ContentType } from '../../domain/entities/content.entity';

export class CreateContentDto {
  @ApiProperty()
  @IsUUID('4')
  organizationId!: string;

  @ApiProperty()
  @IsUUID('4')
  workspaceId!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID('4')
  campaignId?: string;

  @ApiProperty({ example: 'Launch announcement tweet' })
  @IsString()
  @MaxLength(255)
  title!: string;

  @ApiProperty()
  @IsString()
  body!: string;

  @ApiProperty({ enum: ContentType })
  @IsEnum(ContentType)
  type!: ContentType;

  @ApiPropertyOptional({ description: 'True when generated by an AI provider' })
  @IsOptional()
  aiGenerated?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  aiProvider?: string;

  @ApiPropertyOptional({ type: Object })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown>;
}
