import {
  AIAgent,
  BrandBrain,
  CalendarEvent,
  Campaign,
  GenerationHistoryItem,
  IndustryPack,
  IntegrationItem,
  MediaAsset,
  Project,
  TeamMember,
  VoiceProfile,
  WorkflowEdge,
  WorkflowNode,
} from './types';

export const initialBrandBrain: BrandBrain = {
  businessName: 'Acme Technologies',
  industry: 'B2B SaaS & Enterprise Software',
  tagline: 'Supercharging Intelligent Workflows for Modern Teams',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
  brandColors: ['#2563EB', '#6366F1', '#14B8A6', '#0F172A'],
  primaryFont: 'Inter / Plus Jakarta Sans',
  websiteUrl: 'https://acmetech.io',
  productsAndServices: [
    'Acme Cloud Engine',
    'Acme AI Assistant',
    'Workflow Orchestrator',
  ],
  mission: 'To eliminate repetitive digital toil and empower professionals to create high-impact work effortlessly.',
  vision: 'A world where human creativity is amplified 10x by transparent, brand-aligned AI infrastructure.',
  toneOfVoice: ['Professional', 'Authoritative', 'Innovative', 'Approachable', 'Direct'],
  primaryCTA: 'Start Free 14-Day Trial',
  targetAudience: 'Product Managers, Engineering Leaders, Operations Directors, and Marketing Executives at Tech Companies (50-2000 employees).',
  competitors: ['Notion', 'Zapier', 'Linear', 'ClickUp'],
  keywords: ['AI Automation', 'Workflow OS', 'Enterprise Productivity', 'Content Intelligence'],
  socialAccounts: [
    { platform: 'LinkedIn', handle: '@acme-technologies', connected: true },
    { platform: 'Twitter/X', handle: '@acmetech', connected: true },
    { platform: 'YouTube', handle: 'AcmeTechOfficial', connected: true },
    { platform: 'Instagram', handle: '@acmetech_hq', connected: false },
  ],
};

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Q3 Enterprise AI Product Launch',
    category: 'Product Launch',
    status: 'In Progress',
    itemCount: 14,
    lastUpdated: '12 mins ago',
    campaign: 'Q3 Product Expansion',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'proj-2',
    title: 'Weekly Tech Insights Newsletter & Blog',
    category: 'Thought Leadership',
    status: 'In Progress',
    itemCount: 8,
    lastUpdated: '1 hour ago',
    campaign: 'Organic Growth 2026',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'proj-3',
    title: 'Social Media Video Ads Series (LinkedIn/TikTok)',
    category: 'Paid Acquisition',
    status: 'Review',
    itemCount: 6,
    lastUpdated: '3 hours ago',
    campaign: 'Q3 Lead Generation',
    thumbnail: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=400&auto=format&fit=crop&q=80',
  },
  {
    id: 'proj-4',
    title: 'Customer Case Study Video & PDF eBook',
    category: 'Customer Stories',
    status: 'Completed',
    itemCount: 5,
    lastUpdated: 'Yesterday',
    campaign: 'Trust & Reputation',
    thumbnail: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&auto=format&fit=crop&q=80',
  },
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Q3 Enterprise AI Launch',
    status: 'Active',
    platforms: ['LinkedIn', 'Twitter/X', 'YouTube'],
    startDate: '2026-07-01',
    endDate: '2026-08-15',
    contentCount: 24,
    goal: 'Lead Generation',
    reach: '842.5K',
  },
  {
    id: 'camp-2',
    name: 'Summer Developer Bootcamp & Webinar',
    status: 'Active',
    platforms: ['YouTube', 'Blog', 'Email'],
    startDate: '2026-07-10',
    endDate: '2026-08-30',
    contentCount: 16,
    goal: 'Community & Education',
    reach: '310.2K',
  },
  {
    id: 'camp-3',
    name: 'Brand Refresh & Vision 2027',
    status: 'Scheduled',
    platforms: ['LinkedIn', 'Instagram', 'Twitter/X'],
    startDate: '2026-09-01',
    endDate: '2026-10-01',
    contentCount: 10,
    goal: 'Brand Awareness',
    reach: 'Expected 1.2M',
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'How AI Agents are replacing legacy SaaS workflows in 2026',
    platform: 'LinkedIn',
    contentType: 'Carousel / PDF',
    scheduledTime: 'Today, 2:30 PM',
    status: 'Approved',
    author: 'Alex Rivera',
    previewText: 'Static automation is dead. Autonomous AI agents are taking over SaaS. Here are 5 real-world case studies...',
    mediaUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cal-2',
    title: 'Lumora OS Demo: 0 to 10x Content Production in 60s',
    platform: 'YouTube',
    contentType: 'Video Short / Reel',
    scheduledTime: 'Today, 5:00 PM',
    status: 'Approved',
    author: 'Sarah Chen',
    previewText: 'Watch how we turn 1 brand guidelines input into 20 multi-channel assets in under 60 seconds.',
    mediaUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=300&auto=format&fit=crop&q=80',
  },
  {
    id: 'cal-3',
    title: 'The AI Content OS Playbook for Tech Founders',
    platform: 'Newsletter',
    contentType: 'Email Issue #42',
    scheduledTime: 'Tomorrow, 9:00 AM',
    status: 'Review',
    author: 'Alex Rivera',
    previewText: 'In this edition: why prompting is becoming obsolete, and how context graph architectures win...',
  },
  {
    id: 'cal-4',
    title: '3 Mistakes Founders Make When Scaling Content',
    platform: 'Twitter/X',
    contentType: 'Thread',
    scheduledTime: 'Tomorrow, 11:30 AM',
    status: 'Draft',
    author: 'Elena Rostova',
    previewText: '1/ Building isolated prompts instead of brand systems. 2/ Ignoring multi-modal video distribution...',
  },
  {
    id: 'cal-5',
    title: 'Productivity Unlocked: Case Study with Global Tech Inc.',
    platform: 'Blog',
    contentType: 'SEO Article',
    scheduledTime: 'Jul 29, 10:00 AM',
    status: 'Draft',
    author: 'Marcus Vance',
  },
];

export const initialGenerations: GenerationHistoryItem[] = [
  {
    id: 'gen-1',
    title: 'LinkedIn Launch Post for Acme Cloud Engine',
    type: 'LinkedIn Post',
    provider: 'Gemini 3.6 Flash',
    createdAt: '10 mins ago',
    preview: '🚀 Thrilled to announce the official release of Acme Cloud Engine v3.0! Here is how we helped 50+ enterprise teams reduce dev friction by 40%...',
    tags: ['Product Launch', 'B2B', 'Tech'],
  },
  {
    id: 'gen-2',
    title: 'AI Voiceover: Enterprise Security Audio Intro',
    type: 'Voiceover',
    provider: 'ElevenLabs / Cartesia',
    createdAt: '25 mins ago',
    preview: '"Welcome to Acme Security Center. All encryption protocols are verified and active."',
    tags: ['Audio', 'Voice', 'Product'],
  },
  {
    id: 'gen-3',
    title: 'Cyberpunk Cybernetics Thumbnail Graphic',
    type: 'Image Generation',
    provider: 'Flux Pro / Gemini Flash Image',
    createdAt: '1 hour ago',
    preview: 'High resolution 16:9 thumbnail with neon lighting and clean typography overlay.',
    tags: ['Thumbnail', 'Design', 'YouTube'],
  },
  {
    id: 'gen-4',
    title: 'Automated 5-Node Content Repurposing Workflow',
    type: 'Automation Flow',
    provider: 'Lumora Orchestrator',
    createdAt: '2 hours ago',
    preview: 'Blog post -> LinkedIn Carousel + Twitter Thread + YouTube Short Script + Newsletter Summary.',
    tags: ['Automation', 'n8n', 'Workflow'],
  },
];

export const initialAIAgents: AIAgent[] = [
  {
    id: 'ag-1',
    name: 'Research Agent',
    role: 'Market & Topic Intelligence',
    description: 'Scrapes market trends, competitor announcements, and social sentiment to suggest high-converting topics.',
    status: 'Active',
    icon: 'search',
    lastRun: '5 mins ago',
    tasksCompleted: 142,
    accuracy: '98.4%',
    currentTask: 'Analyzing trending Twitter topics in B2B SaaS',
  },
  {
    id: 'ag-2',
    name: 'Strategy Agent',
    role: 'Campaign & Goal Planner',
    description: 'Translates high-level business goals into structured multi-channel campaign briefs and editorial timelines.',
    status: 'Active',
    icon: 'target',
    lastRun: '18 mins ago',
    tasksCompleted: 89,
    accuracy: '99.1%',
    currentTask: 'Optimizing Q3 campaign timeline for peak audience engagement',
  },
  {
    id: 'ag-3',
    name: 'Content Agent',
    role: 'Long-form & Short-form Copywriter',
    description: 'Generates SEO-optimized articles, LinkedIn posts, email newsletters, and Twitter threads infused with Brand Brain tone.',
    status: 'Active',
    icon: 'file-text',
    lastRun: '2 mins ago',
    tasksCompleted: 520,
    accuracy: '97.8%',
    currentTask: 'Drafting LinkedIn carousel post for Q3 product launch',
  },
  {
    id: 'ag-4',
    name: 'Creative Agent',
    role: 'Visual Design & Banner Designer',
    description: 'Creates brand-consistent banners, thumbnail art, social graphics, and slide layouts using brand color palettes.',
    status: 'Idle',
    icon: 'palette',
    lastRun: '1 hour ago',
    tasksCompleted: 312,
    accuracy: '96.5%',
  },
  {
    id: 'ag-5',
    name: 'Video Agent',
    role: 'Scripting & Motion Studio',
    description: 'Transforms text briefs into scene-by-scene video scripts, selects AI avatars, generates B-roll prompts, and edits captions.',
    status: 'Active',
    icon: 'video',
    lastRun: '35 mins ago',
    tasksCompleted: 178,
    accuracy: '95.2%',
    currentTask: 'Generating scene cuts for YouTube Short #14',
  },
  {
    id: 'ag-6',
    name: 'Publishing Agent',
    role: 'Multi-channel Auto-Publisher',
    description: 'Schedules and posts approved content directly to LinkedIn, Twitter/X, YouTube, WordPress, and email service providers.',
    status: 'Active',
    icon: 'send',
    lastRun: 'Today, 2:00 PM',
    tasksCompleted: 840,
    accuracy: '99.9%',
  },
  {
    id: 'ag-7',
    name: 'Analytics Agent',
    role: 'Performance Optimization AI',
    description: 'Monitors real-time metrics across channels, calculates engagement rates, and recommends copy adjustments for underperforming posts.',
    status: 'Active',
    icon: 'bar-chart-2',
    lastRun: 'Continuous',
    tasksCompleted: 1250,
    accuracy: '99.5%',
    currentTask: 'Comparing 30-day CTR performance vs Q2 baseline',
  },
  {
    id: 'ag-8',
    name: 'SEO Agent',
    role: 'Keyword & Search Ranker',
    description: 'Performs keyword gap analysis, generates semantic schema markups, and optimizes articles for top Google rankings.',
    status: 'Idle',
    icon: 'compass',
    lastRun: '3 hours ago',
    tasksCompleted: 210,
    accuracy: '97.1%',
  },
  {
    id: 'ag-9',
    name: 'Repurposing Agent',
    role: '1-to-N Content Multiplier',
    description: 'Takes 1 video or article and automatically generates 10 derivative snippets across all social platforms.',
    status: 'Active',
    icon: 'repeat',
    lastRun: '12 mins ago',
    tasksCompleted: 640,
    accuracy: '98.9%',
    currentTask: 'Splitting 20-min webinar into 5 TikTok shorts',
  },
  {
    id: 'ag-10',
    name: 'Trend Agent',
    role: 'Viral Signal & Meme Detector',
    description: 'Detects emerging viral formats, Audio trends, and industry news events before competitors notice.',
    status: 'Active',
    icon: 'trending-up',
    lastRun: 'Continuous',
    tasksCompleted: 980,
    accuracy: '94.8%',
  },
];

export const initialWorkflowNodes: WorkflowNode[] = [
  {
    id: 'node-1',
    type: 'trigger',
    title: 'New Blog Post Published',
    description: 'Triggers whenever an article is published on WordPress/Ghost',
    icon: 'zap',
    position: { x: 50, y: 150 },
    status: 'success',
  },
  {
    id: 'node-2',
    type: 'agent',
    title: 'Repurposing Agent',
    description: 'Splits article into key takeaways & quotes',
    icon: 'bot',
    position: { x: 320, y: 150 },
    status: 'success',
  },
  {
    id: 'node-3',
    type: 'generate',
    title: 'Generate LinkedIn Carousel & Thread',
    description: 'Applies Brand Brain tone & design system',
    icon: 'sparkles',
    position: { x: 600, y: 80 },
    status: 'success',
  },
  {
    id: 'node-4',
    type: 'generate',
    title: 'Create Voiceover & Video Script',
    description: 'Uses ElevenLabs voice clone & Veo 3.1 video prompts',
    icon: 'mic',
    position: { x: 600, y: 240 },
    status: 'idle',
  },
  {
    id: 'node-5',
    type: 'review',
    title: 'Slack Manager Approval',
    description: 'Sends preview card to #content-approval channel',
    icon: 'check-circle-2',
    position: { x: 900, y: 150 },
    status: 'idle',
  },
  {
    id: 'node-6',
    type: 'publish',
    title: 'Auto Publish & Schedule',
    description: 'Posts to LinkedIn, Twitter/X & YouTube Shorts',
    icon: 'send',
    position: { x: 1180, y: 150 },
    status: 'idle',
  },
];

export const initialWorkflowEdges: WorkflowEdge[] = [
  { id: 'e1-2', source: 'node-1', target: 'node-2' },
  { id: 'e2-3', source: 'node-2', target: 'node-3', label: 'Text Branch' },
  { id: 'e2-4', source: 'node-2', target: 'node-4', label: 'Media Branch' },
  { id: 'e3-5', source: 'node-3', target: 'node-5' },
  { id: 'e4-5', source: 'node-4', target: 'node-5' },
  { id: 'e5-6', source: 'node-5', target: 'node-6', label: 'When Approved' },
];

export const initialIntegrations: IntegrationItem[] = [
  {
    id: 'int-1',
    name: 'Gemini AI Engine',
    category: 'AI Models',
    description: 'Server-side native integration for text, multi-modal reasoning, and video planning.',
    icon: 'sparkles',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-2',
    name: 'OpenAI (GPT-4o)',
    category: 'AI Models',
    description: 'Advanced language generation and structured function calling.',
    icon: 'cpu',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-3',
    name: 'Anthropic Claude 3.5',
    category: 'AI Models',
    description: 'High-precision nuanced writing and long-context documents.',
    icon: 'file-text',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-4',
    name: 'ElevenLabs Voice Engine',
    category: 'Voice & Audio',
    description: 'Ultra-realistic AI voice cloning and multi-lingual voiceover generation.',
    icon: 'mic',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-5',
    name: 'Cartesia Sonic AI',
    category: 'Voice & Audio',
    description: 'Sub-200ms ultra-low latency voice synthesis.',
    icon: 'radio',
    connected: false,
    status: 'Key Required',
  },
  {
    id: 'int-6',
    name: 'Flux Pro / Stable Diffusion',
    category: 'Image & Media',
    description: 'State-of-the-art photorealistic image generation and image editing.',
    icon: 'image',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-7',
    name: 'LinkedIn Business API',
    category: 'Social Platforms',
    description: 'Direct publishing to company pages and personal profiles.',
    icon: 'linkedin',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-8',
    name: 'Twitter / X API v2',
    category: 'Social Platforms',
    description: 'Post threads, polls, and media directly to Twitter/X.',
    icon: 'twitter',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-9',
    name: 'YouTube Data & Shorts API',
    category: 'Social Platforms',
    description: 'Publish videos, shorts, thumbnails, and retrieve audience analytics.',
    icon: 'youtube',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-10',
    name: 'TikTok Creator API',
    category: 'Social Platforms',
    description: 'Publish vertical videos and track viral sound performance.',
    icon: 'video',
    connected: false,
    status: 'Not Configured',
  },
  {
    id: 'int-11',
    name: 'Slack Workspace Bot',
    category: 'Automation',
    description: 'Receive review notifications and approve content drafts directly in Slack.',
    icon: 'message-square',
    connected: true,
    status: 'Connected',
  },
  {
    id: 'int-12',
    name: 'n8n & Zapier Webhooks',
    category: 'Automation',
    description: 'Trigger custom visual workflows and integrate with 5,000+ apps.',
    icon: 'workflow',
    connected: true,
    status: 'Connected',
  },
];

export const initialIndustryPacks: IndustryPack[] = [
  {
    id: 'pack-1',
    title: 'B2B SaaS & Enterprise Software',
    category: 'Technology',
    description: 'Complete operating system for product launches, developer docs, case studies, and LinkedIn thought leadership.',
    icon: 'terminal',
    badge: 'Popular',
    downloads: 14200,
    rating: 4.9,
    includedTemplates: ['Product Launch Campaign', 'Weekly Engineering Digest', 'Customer Case Study Carousel', 'SaaS Growth Threads'],
  },
  {
    id: 'pack-2',
    title: 'E-commerce & D2C Brands',
    category: 'Retail',
    description: 'High-converting ad creatives, product showreel scripts, TikTok viral hooks, and abandoned cart email sequences.',
    icon: 'shopping-bag',
    badge: 'Trending',
    downloads: 18900,
    rating: 4.8,
    includedTemplates: ['UGC Video Script Generator', 'Instagram Story Sales Funnel', 'Flash Sale Banner Templates', 'Product Review Multi-post'],
  },
  {
    id: 'pack-3',
    title: 'Real Estate & Property Development',
    category: 'Real Estate',
    description: 'Virtual walk-through scripts, luxury home social carousel slides, property feature highlights, and neighborhood guides.',
    icon: 'home',
    badge: 'Featured',
    downloads: 8700,
    rating: 4.9,
    includedTemplates: ['Property Tour Voiceover Script', 'Open House Announcement Graphic', 'Market Trend Video Shorts', 'Lead Gen Landing Page'],
  },
  {
    id: 'pack-4',
    title: 'Healthcare & Wellness Clinics',
    category: 'Healthcare',
    description: 'Compliant educational carousels, doctor introduction videos, patient success stories, and wellness newsletters.',
    icon: 'heart-pulse',
    badge: 'Verified',
    downloads: 6300,
    rating: 4.7,
    includedTemplates: ['Medical Educational Carousel', 'Procedure Walkthrough Video', 'Patient Testimonial Layout', 'Weekly Health Digest'],
  },
  {
    id: 'pack-5',
    title: 'Financial Services & Fintech',
    category: 'Finance',
    description: 'Market analysis updates, financial literacy short-form videos, investment guides, and secure client newsletters.',
    icon: 'dollar-sign',
    badge: 'Enterprise',
    downloads: 11400,
    rating: 4.9,
    includedTemplates: ['Weekly Market Wrap Article', 'Fintech Explainer Reel Script', 'Infographic Creator', 'Lead Magnet PDF Generator'],
  },
  {
    id: 'pack-6',
    title: 'Restaurants & Hospitality',
    category: 'Hospitality',
    description: 'Mouth-watering food video hooks, event announcements, chef spotlight reels, and seasonal menu promotions.',
    icon: 'utensils',
    badge: 'New',
    downloads: 9200,
    rating: 4.8,
    includedTemplates: ['Chef Special Reel Template', 'Event Booking Email', 'Food Photography Presets', 'Weekend Promo Pack'],
  },
];

export const initialVoiceProfiles: VoiceProfile[] = [
  {
    id: 'v-1',
    name: 'Sarah - Tech Authority',
    language: 'English (US)',
    gender: 'Female',
    accent: 'American Accent',
    style: 'Confident, Energetic & Crisp',
    isCloned: false,
  },
  {
    id: 'v-2',
    name: 'Marcus - Deep Corporate',
    language: 'English (UK)',
    gender: 'Male',
    accent: 'British Accent',
    style: 'Authoritative, Warm & Trustworthy',
    isCloned: false,
  },
  {
    id: 'v-3',
    name: 'Elena - Modern Narrator',
    language: 'English (US)',
    gender: 'Female',
    accent: 'American Accent',
    style: 'Friendly, Storytelling & Natural',
    isCloned: false,
  },
  {
    id: 'v-4',
    name: 'Alex Rivera (Custom Voice Clone)',
    language: 'English (US)',
    gender: 'Male',
    accent: 'Custom Vocal Clone',
    style: 'Founder Voice, Conversational & Authentic',
    isCloned: true,
  },
];

export const initialMediaAssets: MediaAsset[] = [
  {
    id: 'm-1',
    name: 'Acme_Brand_Logo_Primary_Light.svg',
    type: 'brand',
    size: '124 KB',
    updatedAt: '2 days ago',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    tags: ['Logo', 'Vector', 'Brand Kit'],
  },
  {
    id: 'm-2',
    name: 'Enterprise_AI_Platform_Mockup_4K.png',
    type: 'image',
    size: '2.4 MB',
    updatedAt: '3 hours ago',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    tags: ['Product', 'Dashboard', '4K'],
  },
  {
    id: 'm-3',
    name: 'Customer_Case_Study_Interview_Final.mp4',
    type: 'video',
    size: '48.2 MB',
    updatedAt: 'Yesterday',
    url: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600&auto=format&fit=crop&q=80',
    tags: ['Video', 'Testimonial', '1080p'],
  },
  {
    id: 'm-4',
    name: 'Q3_Product_Launch_Voiceover_Master.mp3',
    type: 'audio',
    size: '4.8 MB',
    updatedAt: '5 hours ago',
    url: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=300&auto=format&fit=crop&q=80',
    tags: ['Audio', 'Voiceover', 'HQ'],
  },
];

export const initialTeamMembers: TeamMember[] = [
  {
    id: 't-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@acmetech.io',
    role: 'Owner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: 'Now',
  },
  {
    id: 't-2',
    name: 'Sarah Chen',
    email: 'sarah.c@acmetech.io',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '12 mins ago',
  },
  {
    id: 't-3',
    name: 'Marcus Vance',
    email: 'marcus.v@acmetech.io',
    role: 'Editor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '1 hour ago',
  },
  {
    id: 't-4',
    name: 'Elena Rostova',
    email: 'elena.r@acmetech.io',
    role: 'Editor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: 'Yesterday',
  },
];
