import {
  BrandBrain,
  MediaAsset,
  TeamMember,
  VoiceProfile,
} from './types';

export const initialBrandBrain: BrandBrain = {
  businessName: 'Acme Technologies',
  industry: 'B2B SaaS & Enterprise Software',
  tagline: 'Supercharging Intelligent Workflows for Modern Teams',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
  brandColors: ['#2563EB', '#6366F1', '#14B8A6', '#0F172A'],
  primaryFont: 'Inter / Plus Jakarta Sans',
  websiteUrl: 'https://acmetech.io',
  productsAndServices: [
    'Acme Cloud Engine',
    'Acme AI Assistant',
    'Workflow Orchestrator',
  ],
  mission: 'To eliminate repetitive digital toil and empower professionals to create high-impact work effortlessly.',
  vision: 'A world where human creativity is amplified 10x by transparent, brand-aligned AI infrastructure.',
  toneOfVoice: ['Professional', 'Authoritative', 'Innovative', 'Approachable', 'Direct'],
  primaryCTA: 'Start Free 14-Day Trial',
  targetAudience: 'Product Managers, Engineering Leaders, Operations Directors, and Marketing Executives at Tech Companies (50-2000 employees).',
  competitors: ['Notion', 'Zapier', 'Linear', 'ClickUp'],
  keywords: ['AI Automation', 'Workflow OS', 'Enterprise Productivity', 'Content Intelligence'],
  socialAccounts: [
    { platform: 'LinkedIn', handle: '@acme-technologies', connected: true },
    { platform: 'Twitter/X', handle: '@acmetech', connected: true },
    { platform: 'YouTube', handle: 'AcmeTechOfficial', connected: true },
    { platform: 'Instagram', handle: '@acmetech_hq', connected: false },
  ],
};

export const initialVoiceProfiles: VoiceProfile[] = [
  {
    id: 'v-1',
    name: 'Sarah - Tech Authority',
    language: 'English (US)',
    gender: 'Female',
    accent: 'American Accent',
    style: 'Confident, Energetic & Crisp',
    isCloned: false,
  },
  {
    id: 'v-2',
    name: 'Marcus - Deep Corporate',
    language: 'English (UK)',
    gender: 'Male',
    accent: 'British Accent',
    style: 'Authoritative, Warm & Trustworthy',
    isCloned: false,
  },
  {
    id: 'v-3',
    name: 'Elena - Modern Narrator',
    language: 'English (US)',
    gender: 'Female',
    accent: 'American Accent',
    style: 'Friendly, Storytelling & Natural',
    isCloned: false,
  },
  {
    id: 'v-4',
    name: 'Alex Rivera (Custom Voice Clone)',
    language: 'English (US)',
    gender: 'Male',
    accent: 'Custom Vocal Clone',
    style: 'Founder Voice, Conversational & Authentic',
    isCloned: true,
  },
];

export const initialMediaAssets: MediaAsset[] = [
  {
    id: 'm-1',
    name: 'Acme_Brand_Logo_Primary_Light.svg',
    type: 'brand',
    size: '124 KB',
    updatedAt: '2 days ago',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    tags: ['Logo', 'Vector', 'Brand Kit'],
  },
  {
    id: 'm-2',
    name: 'Enterprise_AI_Platform_Mockup_4K.png',
    type: 'image',
    size: '2.4 MB',
    updatedAt: '3 hours ago',
    url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    tags: ['Product', 'Dashboard', '4K'],
  },
  {
    id: 'm-3',
    name: 'Customer_Case_Study_Interview_Final.mp4',
    type: 'video',
    size: '48.2 MB',
    updatedAt: 'Yesterday',
    url: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600&auto=format&fit=crop&q=80',
    tags: ['Video', 'Testimonial', '1080p'],
  },
  {
    id: 'm-4',
    name: 'Q3_Product_Launch_Voiceover_Master.mp3',
    type: 'audio',
    size: '4.8 MB',
    updatedAt: '5 hours ago',
    url: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=300&auto=format&fit=crop&q=80',
    tags: ['Audio', 'Voiceover', 'HQ'],
  },
];

export const initialTeamMembers: TeamMember[] = [
  {
    id: 't-1',
    name: 'Alex Rivera',
    email: 'alex.rivera@acmetech.io',
    role: 'Owner',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: 'Now',
  },
  {
    id: 't-2',
    name: 'Sarah Chen',
    email: 'sarah.c@acmetech.io',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '12 mins ago',
  },
  {
    id: 't-3',
    name: 'Marcus Vance',
    email: 'marcus.v@acmetech.io',
    role: 'Editor',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: '1 hour ago',
  },
  {
    id: 't-4',
    name: 'Elena Rostova',
    email: 'elena.r@acmetech.io',
    role: 'Editor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'Active',
    lastActive: 'Yesterday',
  },
];
